In [2]:
import numpy as np

# Character encoding
char_to_idx = {'h': 0, 'e': 1, 'l': 2, 'o': 3}
idx_to_char = {i: c for c, i in char_to_idx.items()}

# One-hot encoding
def one_hot(idx, size=4):
    vec = np.zeros(size)
    vec[idx] = 1
    return vec

# Training data
inputs = ['h', 'e', 'l', 'l']
targets = ['e', 'l', 'l', 'o']

X = np.array([one_hot(char_to_idx[ch]) for ch in inputs])
Y = np.array([char_to_idx[ch] for ch in targets])

# Hyperparameters
input_size = hidden_size = output_size = 4
learning_rate = 0.1

In [3]:
X

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.]])

In [4]:
Y

array([1, 2, 2, 3])

In [5]:
# Initialize weights
# W_xh = np.random.randn(hidden_size, input_size) * 0.1  # input → hidden
# W_hh = np.random.randn(hidden_size, hidden_size) * 0.1  # hidden → hidden
# W_hy = np.random.randn(output_size, hidden_size) * 0.1  # hidden → output

W_xh = np.array([
    [ 0.13309074,  0.17127598, -0.15813858, -0.04525709],
    [-0.09057376, -0.14782509,  0.06502781,  0.14093142],
    [ 0.04669049,  0.01720516,  0.03336642,  0.1781491 ],
    [-0.07548864, -0.02664684,  0.11772184, -0.07503803]
])

W_hh = np.array([[ 0.07809908, -0.13063158,  0.05358797,  0.05681267],
       [ 0.01768576,  0.15217173,  0.23846673,  0.09969253],
       [ 0.09635959,  0.06631399, -0.17052794,  0.00988055],
       [ 0.01199125, -0.01561548,  0.10577997,  0.10847363]])

W_hy = np.array([[ 0.0247689 , -0.11553708,  0.21316413,  0.08569605],
       [-0.05522459, -0.0882109 ,  0.00430406, -0.00389115],
       [ 0.17101969, -0.2330526 , -0.04581541,  0.06289344],
       [ 0.07365608,  0.006953  ,  0.08645168,  0.14256647]])

b_h = np.zeros((hidden_size, 1))
b_y = np.zeros((output_size, 1))

In [6]:
W_xh

array([[ 0.13309074,  0.17127598, -0.15813858, -0.04525709],
       [-0.09057376, -0.14782509,  0.06502781,  0.14093142],
       [ 0.04669049,  0.01720516,  0.03336642,  0.1781491 ],
       [-0.07548864, -0.02664684,  0.11772184, -0.07503803]])

In [7]:
W_hh

array([[ 0.07809908, -0.13063158,  0.05358797,  0.05681267],
       [ 0.01768576,  0.15217173,  0.23846673,  0.09969253],
       [ 0.09635959,  0.06631399, -0.17052794,  0.00988055],
       [ 0.01199125, -0.01561548,  0.10577997,  0.10847363]])

In [8]:
W_hy

array([[ 0.0247689 , -0.11553708,  0.21316413,  0.08569605],
       [-0.05522459, -0.0882109 ,  0.00430406, -0.00389115],
       [ 0.17101969, -0.2330526 , -0.04581541,  0.06289344],
       [ 0.07365608,  0.006953  ,  0.08645168,  0.14256647]])

In [9]:
# Training loop
for epoch in range(2):
    h_prev = np.zeros((hidden_size, 1))
    print(h_prev)
    loss = 0
    grads = {'W_xh': 0, 'W_hh': 0, 'W_hy': 0, 'b_h': 0, 'b_y': 0}
    
    for t in range(len(X)):
        x = X[t].reshape(-1, 1)
        print(x)
        target = Y[t]

        print('components')
        print(x)
        print(h_prev)
        print(W_xh @ x)
        print(W_hh @ h_prev)
        print(b_h)
        print('------------------')

        mid_h = W_xh @ x + W_hh @ h_prev + b_h
        print('mid_h')
        print(mid_h)
        print('----------------')
        # Forward pass
        h = np.tanh(W_xh @ x + W_hh @ h_prev + b_h)
        print('hidden h')
        print(h)
        print('----------------')
        y_logits = W_hy @ h + b_y
        print('y logits')
        print(b_y)
        print(y_logits)
        print('----------')
        y_pred = np.exp(y_logits) / np.sum(np.exp(y_logits))  # softmax
        print('y_pred')
        print(y_pred)
        print('---------')

        # Cross-entropy loss
        loss += -np.log(y_pred[target, 0] + 1e-8)

        # Backpropagation (simple, not through time here)
        dy = y_pred
        dy[target] -= 1  # gradient of loss w.r.t softmax input

        # Gradients
        grads['W_hy'] += dy @ h.T
        grads['b_y'] += dy
        dh = W_hy.T @ dy
        dh_raw = (1 - h ** 2) * dh  # derivative of tanh

        grads['W_xh'] += dh_raw @ x.T
        grads['W_hh'] += dh_raw @ h_prev.T
        grads['b_h'] += dh_raw

        h_prev = h  # move to next time step
        print('next h')
        print(h_prev)
        print('----------------')

    # Update weights
    for param in grads:
        exec(f"{param} -= learning_rate * grads[param]")

    # Print progress
    if epoch % 100 == 0:
        print(f"Epoch {epoch}, Loss: {loss:.4f}")

[[0.]
 [0.]
 [0.]
 [0.]]
[[1.]
 [0.]
 [0.]
 [0.]]
components
[[1.]
 [0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]
 [0.]]
[[ 0.13309074]
 [-0.09057376]
 [ 0.04669049]
 [-0.07548864]]
[[0.]
 [0.]
 [0.]
 [0.]]
[[0.]
 [0.]
 [0.]
 [0.]]
------------------
mid_h
[[ 0.13309074]
 [-0.09057376]
 [ 0.04669049]
 [-0.07548864]]
----------------
hidden h
[[ 0.13231045]
 [-0.09032689]
 [ 0.04665659]
 [-0.07534557]]
----------------
y logits
[[0.]
 [0.]
 [0.]
 [0.]]
[[0.01720198]
 [0.00115502]
 [0.03680228]
 [0.00240921]]
----------
y_pred
[[0.2506774 ]
 [0.24668689]
 [0.25563922]
 [0.24699648]]
---------
next h
[[ 0.13231045]
 [-0.09032689]
 [ 0.04665659]
 [-0.07534557]]
----------------
[[0.]
 [1.]
 [0.]
 [0.]]
components
[[0.]
 [1.]
 [0.]
 [0.]]
[[ 0.13231045]
 [-0.09032689]
 [ 0.04665659]
 [-0.07534557]]
[[ 0.17127598]
 [-0.14782509]
 [ 0.01720516]
 [-0.02664684]]
[[ 0.02035252]
 [-0.00779053]
 [-0.00194126]
 [-0.00024061]]
[[0.]
 [0.]
 [0.]
 [0.]]
------------------
mid_h
[[ 0.1916285 ]
 [-0.15561562]
 [ 

In [10]:
np.exp(y_logits)

array([[0.90283151],
       [0.99776235],
       [1.07232474],
       [1.01332061]])